etetrigger:
  branches:
    include:
      - main  # Set this to the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define variables to avoid hardcoding
  MANIFEST_PATH: 'dashboard/influxdb.yaml'  # Path to your Kubernetes manifest file

stages:
- stage: Deploy
  displayName: "Deploy to AKS"
  jobs:
  - job: DeployToAKS
    displayName: "Deploy NGINX to AKS"
    steps:
    - task: AzureCLI@2
      displayName: 'Set up AKS context'
      inputs:
        azureSubscription: 'azure-devops-service-principal'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks get-credentials --resource-group k8s-learning --name learninig'


    - task: Kubernetes@1
      displayName: 'Deploy NGINX to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'azure-devops-service-principal'
        azureResourceGroup: 'k8s-learning'
        kubernetesCluster: 'learninig'
        namespace: 'kube-system'
        command: 'delete'
        arguments: '-f $(MANIFEST_PATH)'
#        secretType: 'dockerRegistry'
#        containerRegistryType: 'Azure Container Registry'

